import { readFile } from "node:fs/promises";
import { AxeBuilder } from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

for (const cloud of [false, true]) test(`cached images open and export edited copies in ${cloud ? "cloud" : "local"} mode`, async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.route("**/api/settings/onboarding", (route) => route.fulfill({ json: { completed: true, revision: 1 } }));
  if (cloud) await page.addInitScript(() => { Reflect.deleteProperty(CanvasRenderingContext2D.prototype, "filter"); });
  if (cloud) await page.route("**/health", (route) => route.fulfill({ json: { ok: true, mode: "cloud-core" } }));
  const hash = "b".repeat(64);
  const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="320" height="160"><path fill="#ff0000" d="M0 0h160v160H0z"/><path fill="#0000ff" d="M160 0h160v160H160z"/></svg>';
  await page.route(`**/api/assets/${hash}`, (route) => route.fulfill({ contentType: "image/svg+xml", body: svg }));
  const listing = await request.get("/api/documents");
  const headers = { Origin: "http://127.0.0.1:4174", "X-Zhiye-Data-Epoch": listing.headers()["x-zhiye-data-epoch"] };
  const title = `图片验收${cloud}-${Date.now()}`;
  const { document } = await (await request.post("/api/documents", { headers, data: { title } })).json();
  const source = cloud ? `zhiye://asset/${hash}` : "https://images.example.com/cached.png";
  if (!cloud) await page.route(`**/api/documents/${document.id}/assets`, (route) => route.fulfill({ json: [{ documentId: document.id, sourceUrl: source, status: "ready", assetHash: hash, mimeType: "image/svg+xml", byteSize: svg.length, errorCode: null, errorMessage: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }] }));
  const markdown = `# 图片查看\n\n[![双色测试图](${source})](https://example.com/original)\n\n![未缓存图](https://images.example.com/unavailable.png)`;
  const patched = await request.patch(`/api/documents/${document.id}`, { headers, data: { markdown, revision: document.revision } });
  expect(patched.ok()).toBe(true);
  const before = await patched.json();
  const externalRequests: string[] = [];
  page.on("request", (req) => { if (/https:\/\/(?:images\.example\.com|example\.com)/u.test(req.url())) externalRequests.push(req.url()); });
  await page.goto("/");
  await page.locator(".directory-document-row").getByRole("button", { name: title, exact: true }).click();
  if (!cloud) await page.getByRole("button", { name: "预览", exact: true }).click();
  else await expect(page.locator(".cloud-reader")).toBeVisible();
  const trigger = page.getByRole("button", { name: "查看图片：双色测试图", exact: true });
  await expect(async () => { await trigger.scrollIntoViewIfNeeded(); }).toPass({ timeout: 5000 });
  await expect(trigger).toBeEnabled();
  await expect(page.getByRole("button", { name: "查看图片：未缓存图", exact: true })).toHaveCount(0);
  await trigger.focus(); await trigger.press("Enter");
  const viewer = page.getByRole("dialog", { name: "查看图片", exact: true });
  await expect(viewer).toBeVisible();
  await expect.poll(() => viewer.getByRole("img").evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(320);
  const refresh = page.waitForResponse((response) => response.url().includes("/api/documents?") && response.status() === 200);
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("zhiye:extension-saved", { detail: "image-viewer-test" })));
  await refresh;
  await expect(viewer).toBeVisible();
  const bounds = await viewer.boundingBox();
  expect(bounds!.width).toBe(1440); expect(bounds!.height).toBe(900);
  await viewer.getByRole("button", { name: "放大", exact: true }).click();
  await expect(viewer.getByLabel("图片缩放比例")).toHaveText("125%");
  const stage = viewer.getByRole("region", { name: "图片画布" });
  const stageBounds = await stage.boundingBox();
  expect(stageBounds!.width).toBe(1440);
  expect(stageBounds!.height).toBeGreaterThan(400);
  await expect(viewer.getByRole("img")).toBeInViewport();
  await stage.focus(); await stage.press("ArrowRight");
  await expect(viewer.getByRole("img")).toHaveCSS("transform", "matrix(1.25, 0, 0, 1.25, 40, 0)");
  await stage.press("0");
  await viewer.getByRole("button", { name: "左右翻转", exact: true }).click();
  await viewer.getByRole("button", { name: "向右旋转", exact: true }).click();
  await viewer.getByLabel("亮度").fill("125");
  await expect(viewer.getByRole("img")).toHaveCSS("filter", "brightness(1.25) contrast(1)");
  await viewer.getByLabel("亮度").fill("50");
  await viewer.getByLabel("对比度").fill("50");
  const downloadPromise = page.waitForEvent("download");
  await viewer.getByRole("button", { name: "另存图片", exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("zhiye-image-edited.png");
  const file = `/tmp/zhiye-edited-${cloud}.png`;
  await download.saveAs(file);
  const bytes = (await readFile(file)).toString("base64");
  const exported = await page.evaluate(async (base64) => {
    const image = new Image(); image.src = `data:image/png;base64,${base64}`; await image.decode();
    const canvas = document.createElement("canvas"); canvas.width = image.width; canvas.height = image.height;
    const ctx = canvas.getContext("2d")!; ctx.drawImage(image, 0, 0);
    return { width: image.width, height: image.height, top: [...ctx.getImageData(20, 20, 1, 1).data], bottom: [...ctx.getImageData(20, 300, 1, 1).data] };
  }, bytes);
  expect(exported.width).toBe(160); expect(exported.height).toBe(320);
  for (const [actual, expected] of [[exported.top, [64, 64, 128, 255]], [exported.bottom, [128, 64, 64, 255]]]) {
    actual.forEach((channel, index) => expect(Math.abs(channel - expected[index])).toBeLessThanOrEqual(1));
  }
  expect((await new AxeBuilder({ page }).include(".image-viewer").analyze()).violations).toEqual([]);
  await page.screenshot({ path: `/tmp/zhiye-image-viewer-${cloud}-desktop.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { document.documentElement.dataset.theme = "dark"; });
  await page.screenshot({ path: `/tmp/zhiye-image-viewer-${cloud}-mobile.png` });
  expect((await viewer.boundingBox())!.height).toBe(844);
  await viewer.getByRole("button", { name: "恢复原样", exact: true }).click();
  await expect(viewer.getByRole("button", { name: "左右翻转", exact: true })).toHaveAttribute("aria-pressed", "false");
  await page.keyboard.press("Escape"); await expect(viewer).toHaveCount(0);
  await expect(trigger).toBeFocused();
  expect((await (await request.get(`/api/documents/${document.id}`)).json())).toMatchObject({ markdown, revision: before.revision });
  expect(externalRequests).toEqual([]);
});
