import { AxeBuilder } from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

test.beforeEach(async ({ page }) => {
  await page.route("**/api/settings/onboarding", (route) => route.fulfill({ json: { completed: true, revision: 1 } }));
  await page.emulateMedia({ reducedMotion: "reduce" });
});

test("settings retain AI fields across categories and save the reading margin", async ({ page, request }) => {
  const listing = await request.get("/api/documents");
  const headers = { Origin: "http://127.0.0.1:4174", "X-Zhiye-Data-Epoch": listing.headers()["x-zhiye-data-epoch"] };
  const title = `阅读设置${Date.now()}`;
  const created = await request.post("/api/documents", { headers, data: { title } });
  expect(created.ok()).toBe(true);
  await page.goto("/");
  const defer = page.getByRole("button", { name: "稍后设置", exact: true });
  if (await defer.isVisible()) await defer.click();
  await page.getByRole("button", { name: title, exact: true }).click();
  await page.getByLabel("Markdown 编辑器").fill("# 阅读测试\n\n用于验证正文的百分比边距。");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await expect(page.getByText("已保存", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "打开设置", exact: true }).click();
  await expect(page.getByRole("heading", { name: "设置", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "远程 HTTPS", exact: true }).click();
  const model = page.getByRole("textbox", { name: "AI 远程模型", exact: true });
  await model.fill("unsaved-model");
  await page.getByRole("button", { name: "阅读与显示", exact: true }).click();
  const margin = page.getByRole("spinbutton", { name: "正文两侧总留白百分比" });
  await margin.fill("50");
  await expect(page.locator(".app-shell")).toHaveCSS("--reading-margin", "50");
  await page.getByRole("button", { name: "AI 派生设置", exact: true }).click();
  await expect(model).toHaveValue("unsaved-model");
  await page.getByRole("button", { name: "阅读与显示", exact: true }).click();
  const violations = (await new AxeBuilder({ page }).include(".workspace-settings").analyze()).violations;
  expect(violations).toEqual([]);
  await page.getByRole("button", { name: "返回资料库", exact: true }).click();
  await page.getByRole("button", { name: "预览", exact: true }).click();
  await expect(page.locator(".markdown-preview")).toHaveCSS("max-width", "none");
  const dimensions = await page.locator(".markdown-preview").evaluate((el) => ({ width: el.getBoundingClientRect().width, padding: parseFloat(getComputedStyle(el).paddingLeft) }));
  expect(dimensions.padding / dimensions.width).toBeCloseTo(.25, 2);
  await page.reload();
  await expect(page.locator(".app-shell")).toHaveCSS("--reading-margin", "50");
  await page.getByRole("button", { name: "打开设置", exact: true }).click();
  await page.getByRole("button", { name: "阅读与显示", exact: true }).click();
  await margin.fill("0");
  await page.screenshot({ path: "/tmp/zhiye-reading-settings-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "/tmp/zhiye-reading-settings-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "恢复默认留白", exact: true }).click();
  await expect(margin).toHaveValue("20");
});

 test("original page is available only in the row actions, including trash", async ({ page }) => {
  await page.goto("/");
  const defer = page.getByRole("button", { name: "稍后设置", exact: true });
  if (await defer.isVisible()) await defer.click();
  const url = `https://example.com/image-viewer-${Date.now()}`;
  await page.getByLabel("网页地址").fill(url);
  await page.getByRole("button", { name: "收取网页" }).click();
  const row = page.locator(".directory-document-row").filter({ has: page.locator(`a[href="${url}"]`) });
  await expect(row).toBeVisible();
  await expect(row.locator(".directory-external")).toHaveCount(0);
  await expect(row.getByRole("link", { name: /打开原网页/ })).toBeHidden();
  await row.getByRole("button", { name: /更多操作/ }).click();
  const link = page.getByRole("link", { name: /打开原网页/ });
  await expect(link).toHaveAttribute("href", url);
  await expect(link).toHaveAttribute("rel", "noreferrer noopener");
  await link.press("Escape");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "文档资料库", exact: true }).click();
  const rowBounds = await row.boundingBox();
  const moreBounds = await row.getByRole("button", { name: /更多操作/ }).boundingBox();
  expect(rowBounds!.x + rowBounds!.width - moreBounds!.x - moreBounds!.width).toBeLessThanOrEqual(2);
  await page.screenshot({ path: "/tmp/zhiye-directory-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await row.locator(".directory-title").click();
  await row.getByRole("button", { name: /更多操作/ }).click();
  await page.getByRole("button", { name: "删除（移入回收站）", exact: true }).click();
  await page.getByRole("alertdialog").getByRole("button", { name: "移入回收站", exact: true }).click();
  await expect(page.getByRole("navigation", { name: "目录分类" }).getByRole("button", { name: "回收站", exact: true })).toHaveAttribute("aria-pressed", "true");
  await row.getByRole("button", { name: /更多操作/ }).click();
  await expect(link).toBeVisible();
  await expect(page.getByRole("button", { name: "删除（移入回收站）", exact: true })).toHaveCount(0);
 });
